// <auto-generated />
using System;
using ContractsBot.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MafiaContractsBot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MafiaContractsBot.Features.ContractsRanking.CompletedContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ContractThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("CompletedContracts");
                });

            modelBuilder.Entity("MafiaContractsBot.Features.ContractsRanking.Contract", b =>
                {
                    b.Property<ulong>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ThreadId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("MafiaContractsBot.Features.ContractsRanking.ContractUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContractUsers");
                });

            modelBuilder.Entity("MafiaContractsBot.Features.ContractsRanking.CompletedContract", b =>
                {
                    b.HasOne("MafiaContractsBot.Features.ContractsRanking.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MafiaContractsBot.Features.ContractsRanking.ContractUser", "User")
                        .WithMany("CompletedContracts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MafiaContractsBot.Features.ContractsRanking.ContractUser", b =>
                {
                    b.Navigation("CompletedContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
